# -*- coding: utf-8 -*-
"""email identification3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBZbTavOwJMqozniFo60iNsl5hhbPHP4
"""

import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

data = pd.read_csv(url, sep='\t', names=['label', 'message'])

print(data.head())

# Convert labels to numbers
data['label'] = data['label'].map({'ham': 0, 'spam': 1})

print(data.head())

from sklearn.model_selection import train_test_split

X = data['message']   # TEXT
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(type(X_train))   # MUST be pandas Series

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)   # ONLY ONCE
X_test = vectorizer.transform(X_test)

print(type(X_train))   # csr_matrix = correct

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

print("Model trained ✅")

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

msg = ["Congratulations! You won a free prize"]

msg_vec = vectorizer.transform(msg)

prediction = model.predict(msg_vec)

if prediction[0] == 1:
    print("Spam Message 🚫")
else:
    print("Not Spam ✅")